/* To add a new game: create games/<id>/index.html and add one entry here. */
const GAMES = [
  {
    id: 'odd-one-out',
    emoji: '🕵️',
    title: 'Odd One Out',
    blurb: 'Deep flag lore — which one doesn’t belong?',
    color: 'var(--red)',
    bestKey: 'odd-one-out',
    bestLabel: (b) => `Best: ${b} / 10`,
  },
  {
    id: 'faked-flags',
    emoji: '🚨',
    title: 'Fake Flag Detector',
    blurb: 'Real flag… or sneakily doctored?',
    color: 'var(--teal)',
    bestKey: 'faked-flags',
    bestLabel: (b) => `Best: ${b} / 10`,
  },
  {
    id: 'flag-forge',
    emoji: '⚒️',
    title: 'Flag Forge',
    blurb: 'Build flags from memory, piece by piece',
    color: 'var(--purple)',
    bestKey: 'flag-forge',
    bestLabel: (b) => `Best: ${b} / 60`,
  },
  {
    id: 'time-machine',
    emoji: '⏳',
    title: 'Time Machine',
    blurb: 'Flags that no longer fly — whose were they?',
    color: '#ff9f43',
    bestKey: 'time-machine',
    bestLabel: (b) => `Best: ${b} pts`,
  },
  {
    id: 'speed-sort',
    emoji: '⚡',
    title: 'Speed Sort',
    blurb: '45 seconds, two bins — sort flags fast!',
    color: 'var(--green)',
    bestKey: 'speed-sort',
    bestLabel: (b) => `Best: ${b} sorted`,
  },
  {
    id: 'flag-mashup',
    emoji: '🧬',
    title: 'Frankenflag',
    blurb: 'Which flags were stitched into this monster?',
    color: '#ff6bd6',
    bestKey: 'flag-mashup',
    bestLabel: (b) => `Best: ${b} donors`,
  },
  {
    id: 'ratio-nerd',
    emoji: '📐',
    title: 'Ratio Nerd',
    blurb: 'Proportion pedantry — how long is that flag really?',
    color: '#5aa9e6',
    bestKey: 'ratio-nerd',
    bestLabel: (b) => `Best: ${b} / 10`,
  },
  {
    id: 'zoomed-in',
    emoji: '🔬',
    title: 'Way Too Close',
    blurb: 'Name the flag from a tiny detail — buzz in early!',
    color: 'var(--yellow)',
    bestKey: 'zoomed-in',
    bestLabel: (b) => `Best: ${b} pts`,
  },
];
